#include"stdio.h"
//水仙花数，即拆分各数位的数三次方之和仍为这个数 
main(){
	int n,a,b,c,z,x,s=0;
	printf("输入查找的范围(包括边界)：");
	scanf("%d%d",&z,&c);
	for(n=z;n<=c;n++){
		a=n%10;
		n/=10;
		b=n%10;
		c=n;
		if(a*a*a+b*b*b+c*c*c==n){
			s++;
			printf("范围内第%d个水仙花数为%d\n",s,n);
		}
		if(s==0)
			printf("范围内没有水仙花数");
	}
}
